# Generated by Django 4.0.3 on 2022-03-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
